Explicitly build with -std=gnu++03.
The port fails to build with C++11 and later. GCC 6 uses -std=gnu++14 by
default, and fails like this:

xmlParser.cpp: In function 'char* stringDup(const char*, int)':
xmlParser.cpp:464:36: error: cast from 'std::nullptr_t' to 'char' loses precision [-fpermissive]
         lpszNew[cbData] = (XMLCHAR)NULL;

Since this version of animorph is from 2007 and the code has completely changed
upstream (it does not even use C++ anymore), there is little point in fixing
the code instead of just making it build like it did before.

PR:		219279
Approved by:	portmgr (blanket approval)