Fix games/cockatrice plist. With CMake 3.10, (also CMake 3.11, which is why I noticed this) and Qt 5.9, there are translations that are not included in the plist. Poudriere shows me:
	====> Running Q/A tests (stage-qa)
	====> Checking for pkg-plist issues (check-plist)
	===> Parsing plist
	===> Checking for items in STAGEDIR missing from pkg-plist
	Error: Orphaned: %%DATADIR%%/translations/cockatrice_ca.qm
	Error: Orphaned: %%DATADIR%%/translations/cockatrice_el.qm
<snip>

Approved by:	tcberner (mentor)
Differential Revision:	https://reviews.freebsd.org/D14784