devel/libosinfo: fix build with GCC-based architectures
C11 is now required:
../osinfo/osinfo_tree.h:63: error: redefinition of typedef 'OsinfoTree'
../osinfo/osinfo_install_script.h:44: error: previous declaration of 'OsinfoTree' was here

Approved by:	mentors (implicit approval)