- Add patches to fix build on 10.x+ - Mark BROKEN on 10.x+
It accesses field of structure which was made opaque in r235647
to change internally used file descriptor:

cwd.c:892:15: error: incomplete definition of type 'struct _dirdesc'
    search->dp->dd_fd = squirrel_fd(search->dp->dd_fd);
    ~~~~~~~~~~^
/usr/include/dirent.h:58:8: note: forward declaration of 'struct _dirdesc'
struct _dirdesc;
       ^

This hack is no longer possible on 10.x+. Doscmd may work fine
without it though, but I'm not taking responsibility by blindly
removing it. If you know the interlans and can test it, see
extra-patch-cwd.c.