- Fix LICENSE - Switch to options helpers - Do not stage unneeded files properly to fix stage-qa:
    Error: '/bin/bash' is an invalid shebang you need USES=shebangfix for 'bin/euktoeps.orig.bak'

Approved by:	portmgr blanket