www/gohugo: Update to 0.62.0, unbreak on aarch64
- Update to 0.62.0

- Unbreak on aarch64:

# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go:400:12: undefined: uint128

Unbreak by updating golang.org/x/sys to 33540a1f6037 which adds support for
freebsd/arm64. Upstream PR: https://github.com/gohugoio/hugo/pull/6671

Changes:	https://github.com/gohugoio/hugo/releases/tag/v0.62.0
PR:		242882, 242312
Submitted by:	ben.lavery@hashbang0.com (maintainer)