We need iconv from ports for the "//TRANSLIT" extension
$ aqhbci-tool4 getaccsepa -b 111111111 -a 2222222222
3:2018/02/18 08-02-57:gwen(32628):gui.c:  179: Cannot convert from "US-ASCII//TRANSLIT" to "UTF-8", Invalid argument
3:2018/02/18 08-02-57:gwen(32628):args.c:   71: Error parsing "-b"
ERROR: Could not parse arguments

Reported by:	aqbanking-user mailing list (archives only available to subscribers)