@snkmail.com n shebangs to use the specified PYTHON_CMD (stage-qa fix) [1]
Add missing html file in plist (check-orphans) [2]

Also we don't need -DENABLE_BAD_BOOST=ON since the ports version of boost is now at 1.65.

  info about ENABLE_BAD_BOOST in GrBoost.cmake...
  # Boost 1.52 disabled, see https://svn.boost.org/trac/boost/ticket/7669
  # Similar problems with Boost 1.46 and 1.47.

stage-qa, check-orphans and poudriere testport all pass now with the attached patch.

[1]
====> Running Q/A tests (stage-qa)
Error: '/usr/local/bin/python2' is an invalid shebang you need USES=shebangfix for 'bin/volk_modtool'
Error: '/usr/local/bin/python2' is an invalid shebang you need USES=shebangfix for 'bin/gnuradio-companion'
Error: '/usr/local/bin/python2' is an invalid shebang you need USES=shebangfix for 'bin/polar_channel_construction'
 .
 .

[2]
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/html/gr-trellis.html

PR:		ports/225126
Submitted by:	John Hein <z7dr6ut7gs@snkmail.com>


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@458982 35697150-7ecd-e111-bb59-0022644237b5