emulators/mupen64plus-video-glide64mk2: unbreak with clang 3.9
./../src/Glide64/3dmath.cpp:274:5: error: use of undeclared identifier '__builtin_ia32_storeups'
    __builtin_ia32_storeups(r[i], destrow);
    ^

PR:		212343
Regressed by:	https://github.com/llvm-mirror/clang/commit/53a73530fec1