- Add LICENSE - Mark BROKEN on 9.x: does not build due to incompatibility with GraphicsMagic:
/usr/local/lib/libGraphicsMagick++.so: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)@GLIBCXX_3.4.15'

Approved by:	portmgr blanket