Fix on head by setting LLD_UNSAFE:
ld: error: /usr/lib/libpmc.so: undefined reference to std::__1::__basic_string_common<true>::__throw_length_error() const
ld: error: /usr/lib/libpmc.so: undefined reference to std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long)
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Since I'm here, add USES=gl.