MFH: r484946
multimedia/gnome-mpv: chase compiler used by mpv

On GCC architectures OPENCV option in multimedia/ffmpeg appears to
require consumers to pass -L${_GCC_RUNTIME}. So, use modern GCC where
this is implicit.

//usr/local/lib/libopencv_core.so.3.4: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
//usr/local/lib/libopencv_core.so.3.4: undefined reference to `std::__throw_bad_function_call()@GLIBCXX_3.4.14'

PR:		233120
Submitted by:	linimon
Approved by:	ports-secteam blanket