MFH: r445053
Only use enable-ec_nistp_64_gcc_128 on amd64 since it requires a
64-bit little-endian architecture and fix the build on !amd64

ecp_nistp224.c:43:9: error: unknown type name '__uint128_t'
typedef __uint128_t uint128_t;	/* nonstandard; implemented by gcc on 64-bit
	^

PR:		220403
Reported by:	dewayne@heuristicsystems.com.au
Approved by:	mat (mentor)
Differential Revision:	https://reviews.freebsd.org/D11436

Approved by:	ports-secteam (blanket)