www/py-clientform: convert to USES=python
- convert to USES=python
- limit to python2:
  """
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 13
    False, True = 0, 1
       ^
  SyntaxError: can't assign to keyword
  """

Approved by:	portmgr (blanket)