games/tesseract-data: pacify check-plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir %%DATADIR%%/media/prefab
Error: Orphaned: @dir %%DATADIR%%/screenshot

PR:		189829
Pointy hat:	jbeich (last minute regression)
Reported by:	marino