www/webkit2-gtk3: attempt to unbreak on aarch64
./Source/JavaScriptCore/assembler/ARM64Assembler.h:2760:2: error: "The cacheFlush support is missing on this platform."
 #error "The cacheFlush support is missing on this platform."
  ^

./Source/JavaScriptCore/assembler/MacroAssemblerARM64.h:133:17: error: class member cannot be redeclared
    static bool shouldBlindForSpecificArch(uintptr_t value) { return value >= 0x00ffffff; }
                ^
./Source/JavaScriptCore/assembler/MacroAssemblerARM64.h:132:17: note: previous declaration is here
    static bool shouldBlindForSpecificArch(uint64_t value) { return value >= 0x00ffffff; }
                ^

Reported by:	pkg-fallout