sysutils/flowgger: unbreak with OpenSSL 1.1.1
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.

', cargo-crates/openssl-sys-0.9.21/build.rs:486:9

Reported by:	pkg-fallout