- Mark BROKEN on i386: does not build, uses some broken type instead of size_t
./Object.hpp:226:11: error: 'operator new' takes type size_t ('unsigned int') as first parameter
    void* operator new       (const t_size size);
          ^
./Object.hpp:227:11: error: 'operator new[]' takes type size_t ('unsigned int') as first parameter
    void* operator new    [] (const t_size size);
          ^
2 errors generated.

Approved by:	portmgr blanket