sysutils/py-azure-cli: Update to 2.0.72
- Port changes

  Almost all sysutils/py-azure-cli-* ports were incorporated into
  py-azure-cli.

  This update replaces all those dependencies to their
  devel/py-azure-mgmt-* port directly, eliminating a level in the
  dependency chain.

  sysutils/py-azure-cli
   --> sysutils/py-azure-cli-XYZ  (GONE)
     --> devel/py-azure-mgmt-XYZ

  Now we will be able to remove ~50 sysutils/py-azure-cli-* ports
  from the ports tree.

- Add patches to fix an issue with the Policy API
  >>> ImportError: cannot import name 'PolicyMode'


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@511522 35697150-7ecd-e111-bb59-0022644237b5