misc/opennn: Fix build
Change to clang-9 because clang-10 failed:
error: no matching constructor for initialization of 'const Vector<size_t>' (aka 'const Vector<unsigned long>')
https://github.com/Artelnics/OpenNN/issues/105

Reported by:	fallout