- Mark broken on 9.x:
app.c: In function 'xmlsec_TransformHmacSha256Id':
app.c:349: error: 'xmlSecOpenSSLTransformHmacSha256Id' undeclared (first use in this function)
app.c:349: error: (Each undeclared identifier is reported only once
app.c:349: error: for each function it appears in.)
app.c: In function 'xmlsec_TransformRsaSha256Id':
app.c:430: error: 'xmlSecOpenSSLTransformRsaSha256Id' undeclared (first use in this function)
app.c: In function 'xmlsec_TransformSha256Id':
app.c:488: error: 'xmlSecOpenSSLTransformSha256Id' undeclared (first use in this function)
error: command 'cc' failed with exit status 1

- Add missing USES=ssl
- Remove NO_ARCH, this port installs a shared library