comms/airspy: Fix build due to the MMX-related errors
Fix errors like this:
error: always_inline function '_mm_loadu_ps' requires target feature 'mmx',
       but would be inlined into function 'x' that is compiled without support for 'mmx'

Reported by:	fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@473418 35697150-7ecd-e111-bb59-0022644237b5