www/firefox: require new NSS after r534912/r534914
In file included from Unified_c_netwerk_srtp_src0.c:2:
netwerk/srtp/src/crypto/cipher/aes_gcm_nss.c:274:15: error: no member named 'ulIvBits' in 'struct CK_GCM_PARAMS'
    c->params.ulIvBits = GCM_IV_LEN * 8;
    ~~~~~~~~~ ^

PR:		246690
Reported by:	mikael