Attempt to fix build on GCC-based systems by removing stray ";" characters. This fix should go upstream.
However, at least on powerpc64, the patch is necessary but insufficient:

  src/library/tools/tune/tune.c:137: error: 'CLOCK_REALTIME' undeclared (first use in this function)

After spending some time examining the wrkdir, I can't find its declaration.
OTOH the build succeeds on amd64.

This may need to be worked on by the upstream.

Approved by:	portmgr (tier-2 blanket)