Mark BROKEN: Does not build
/wrkdirs/usr/ports/graphics/pinta/work/pinta-1.4/Pinta.Core/Pinta.Core.csproj (default targets) ->
/usr/local/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	Classes/IExtension.cs(5,12): error CS0234: The type or namespace name `Addins' does not exist in the namespace `Mono'. Are you missing an assembly reference?
	Effects/BaseEffect.cs(30,12): error CS0234: The type or namespace name `Addins' does not exist in the namespace `Mono'. Are you missing an assembly reference?
	Managers/SystemManager.cs(33,12): error CS0234: The type or namespace name `Addins' does not exist in the namespace `Mono'. Are you missing an assembly reference?
	Classes/BaseTool.cs(32,12): error CS0234: The type or namespace name `Addins' does not exist in the namespace `Mono'. Are you missing an assembly reference?
	Classes/BasePaintBrush.cs(28,12): error CS0234: The type or namespace name `Addins' does not exist in the namespace `Mono'. Are you missing an assembly reference?

Reported by:	pkg-fallout