x11/phosh: add missing dependency after r549544
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/applications/sm.puri.OSK0.desktop
Error: Missing: share/applications/sm.puri.Phosh.desktop
Error: Missing: share/gnome-session/sessions/phosh.session
Error: Missing: share/locale/am/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/ar/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/bg/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/ca/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/cs/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/da/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/de/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/el/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/en_GB/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/eo/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/es/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/es_ES/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/eu/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/fa/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/fi/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/fr/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/fur/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/he/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/hu/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/it/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/ja/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/ko/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/la/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/nb/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/nl/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/pl/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/pt_BR/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/pt_PT/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/ro/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/ru/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/sk/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/sr/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/sv/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/tr/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/uk/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/zh_Hans_CN/LC_MESSAGES/phosh.mo
Error: Missing: share/locale/zh_TW/LC_MESSAGES/phosh.mo
===> Error: Plist issues found.