Add -Wno-error=narrowing when the architecture has base GCC (and thus uses new GCC from ports) to prevent the following:
DoublePinyinTable.h:86:1: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]

While here, pet portlint.

PR:		235105
Submitted by:	Piotr Kubaj
Approved by:	portmgr (tier-2 blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@491022 35697150-7ecd-e111-bb59-0022644237b5