devel/open-usp-tukubai: Fix shebangs of installed commands
Error: '/usr/bin/env python' is an invalid shebang you need USES=shebangfix for 'bin/getfirst'
etc.

It is also not compatible with Python 3.x since it uses the old
print statement in many places.

- Add LICENSE, NO_ARCH while here