- py-pyro requires at least Python 2.5, so update the USE_PYTHON variable.
  Build output with Python forced to version 2.4:

===>   py24-pyro-4.1 depends on file: /usr/local/bin/python2.4 - found
===>  Configuring for py24-pyro-4.1
Traceback (most recent call last):
  File "setup.py", line 6, in ?
    import Pyro.constants
  File "src/Pyro/__init__.py", line 10, in ?
    raise RuntimeError("Pyro requires at least Python 2.5")
RuntimeError: Pyro requires at least Python 2.5
*** Error code 1
Stop in /a/ports/devel/py-pyro.