devel/liteide: Unbreak on aarch64
http://thunderx1.nyi.freebsd.org/data/head-arm64-default/p520537_s355573/logs/errors/liteide-36.2_1.log

# github.com/kr/pty
vendor/github.com/kr/pty/pty_freebsd.go:50:20: undefined: fiodgnameArg
vendor/github.com/kr/pty/pty_freebsd.go:63:12: undefined: _C_SPECNAMELEN
vendor/github.com/kr/pty/pty_freebsd.go:66:9: undefined: fiodgnameArg

The fix was merged by upstream as https://github.com/visualfc/gotools/pull/12

PR:		242312


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@521222 35697150-7ecd-e111-bb59-0022644237b5