cad/openvsp: fix build on non-x86
Don't use amd64 code on all 64-bit architectures.
Include sys/param.h because of:
/usr/local/poudriere/ports/default/cad/openvsp/work/OpenVSP-OpenVSP_3.19.0/src/util/FileUtil.cpp:118:18: error: 'PATH_MAX' was not declared in this scope
  118 |     char exepath[PATH_MAX];
      |                  ^~~~~~~~

PR:		242235
Approved by:	fernape (maintainer), tcberner (mentor)
Differential Revision:	https://reviews.freebsd.org/D22576