databases/opendbx: add USES+= readline
This started failing without a recent change to opendbx, so a dependency
most have stopped pulling in readline.  The configure error was:

   error: readline library (libreadline) not found

approved by:	blanket