- Update to 1.8.2 - Update URL in pkg-descr to avoid a redirection - Add a patch and a post-extract-* target to fix a couple of Sphinx exceptions during the build process:
1)

WARNING: autodoc: failed to import module u'webob.client'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named webob.client

2)

Exception occurred:
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'webob' distribution was not found and is required by the application
The full traceback has been saved in /tmp/sphinx-err-Kjn2DB.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
*** Error code 1

Changes:	https://docs.pylonsproject.org/projects/webob/en/stable/changes.html


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@477168 35697150-7ecd-e111-bb59-0022644237b5