devel/RStudio: unbreak with boost 1.69
CMake Error at /usr/local/share/cmake/Modules/FindBoost.cmake:2049 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.69.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries:

          boost_signals

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  src/cpp/CMakeLists.txt:208 (find_package)

In file included from src/cpp/core/r_util/RSourceIndex.cpp:24:
In file included from src/cpp/core/include/core/r_util/RSourceIndex.hpp:36:
src/cpp/core/include/core/r_util/RFunctionInformation.hpp:78:33: error:
      no viable conversion from returned value of type 'const boost::tribool' to function return type 'bool'
   bool isUsed() const { return isUsed_; }
                                ^~~~~~~
src/cpp/core/include/core/r_util/RFunctionInformation.hpp:80:47: error:
      no viable conversion from returned value of type 'const boost::tribool' to function return type 'bool'
   bool isMissingnessHandled() const { return isMissingnessHandled_; }
                                              ^~~~~~~~~~~~~~~~~~~~~
src/cpp/core/include/core/r_util/RFunctionInformation.hpp:133:14: error:
      no viable conversion from returned value of type 'boost::logic::tribool' to function return type 'bool'
      return isPrimitive_ == true;
             ^~~~~~~~~~~~~~~~~~~~
src/cpp/session/modules/SessionRParser.cpp:411:14: error: no viable conversion from returned value of type 'boost::tribool' to function return type 'bool'
      return fnInfo.performsNse();
             ^~~~~~~~~~~~~~~~~~~~

PR:		232525
Obtained from:	upstream (signals)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@483800 35697150-7ecd-e111-bb59-0022644237b5