Mark broken: does not build
c++ -c -O2 -pipe -fno-strict-aliasing -O2 -pthread -D_THREAD_SAFE -Wall -W -fPIC -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/share/qt4/mkspecs/freebsd-clang -I. -I/usr/local/include/qt4/QtCore -I/usr/local/include/qt4/QtNetwork -I/usr/local/include/qt4/QtGui -I/usr/local/include/qt4/QtXml -I/usr/local/include/qt4 -I../src -I. -I/usr/local/include/qt4 -I/usr/local/include -o qtsoap.o ../src/qtsoap.cpp
In file included from ../src/qtsoap.cpp:40:
../src/qtsoap.h:44:10: fatal error: 'QtXml/QtXml' file not found
#include <QtXml/QtXml>

Reported by:	pkg-fallout since november 2013