games/palomino: Fix build with Clang 6
src/collision/collision.cc:173:44: error: no matching function for call to 'make_pair'
                EVENT_COLLISION.Broadcast( std::make_pair< shptr<Object>, shptr<Object> >( dyna.PTR(), collidable ) );
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/utility:639:1: note: candidate function not viable: no known conversion from 'shptr<object::Object>' to 'base::shptr<object::Object> &&' for 2nd argument
make_pair(_T1&& __t1, _T2&& __t2)
^

... and more of these in too many files to patch

http://beefy11.nyi.freebsd.org/data/head-i386-default/p478276_s338342/logs/errors/palomino-20131231_6.log


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@478662 35697150-7ecd-e111-bb59-0022644237b5