. When building libsplashscreen, put the internal JDK header paths before   the external system header paths.  This prevents us from picking up the   jpeg headers from the system headers when building splashscreen_jpeg.c   which caused an undefined reference to be present in libsplashscreen   since the internal JDK jpeg headers remap the function names.
PR:		119654