When you remove a Python version from a port (security/py-pysaml2 here) you have to make sure the ports that depend on it will not try to use that version, otherwise it breaks bulk -a.
Error: compute_deps_pkg failed to lookup pkgname for security/py-pysaml2@py35 processing package py35-matrix-synapse-1.7.2_1 from net-im/py-matrix-synapse@py35 -- Is SUBDIR+=py-pysaml2@py35 missing in security/Makefile and does the port provide the 'py35' FLAVOR?
Error: compute_deps_pkg failed to lookup existing pkgname for security/py-pysaml2@py35 processing package py35-matrix-synapse-1.7.2_1
Error: compute_deps_pkg failed to lookup pkgname for security/py-pysaml2@py35 processing package py35-keystone-13.0.0_1 from security/py-keystone@py35 -- Is SUBDIR+=py-pysaml2@py35 missing in security/Makefile and does the port provide the 'py35' FLAVOR?
Error: compute_deps_pkg failed to lookup existing pkgname for security/py-pysaml2@py35 processing package py35-keystone-13.0.0_1

Pointy hat:	sunpoet