x11-drivers/xf86-input-wacom: update to 0.34.0 and fix stage-qa
Error: /usr/local/bin/xsetwacom is linked to /usr/local/lib/libX11.so.6 from x11/libX11 but it is not declared as a dependency
Warning: you need USE_XORG+=x11
Error: /usr/local/bin/xsetwacom is linked to /usr/local/lib/libXext.so.6 from x11/libXext but it is not declared as a dependency
Warning: you need USE_XORG+=xext

Changes:	https://sourceforge.net/p/linuxwacom/mailman/message/35533919/