graphics/reallyslick: fix build
Switch to ports GCC to fix:
/usr/local/lib/libgraphite2.so.3: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'

Approved by:	mentors (implicite approval)