Mk/Uses/cargo.mk: Unbreak install with rust-nightly
Remove yet another install metadata file.  This should all be
replaced with --no-track once it is part of lang/rust.

https://github.com/rust-lang/cargo/pull/7560

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: .crates2.json


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@523913 35697150-7ecd-e111-bb59-0022644237b5