Upgrade multimedia/plexhometheater to v1.2.2
The attached patch upgrades multimedia/plexhometheater to v1.2.2.

In addition, it removes the LIBDEPENDS on audio/lame and java as neither are
actually used by plexhometheater, and adds a pkg-message to explain how to run
plexhometheater from the command line when the package is installed.

---

Plexhometheater is unable to play videos, with some of the following error
messages appearing in the logs depending on the codec of the video being
played.

ERROR: Unable to load
/usr/local/lib/plexhometheater/system/players/dvdplayer/avcodec-53-x86-freebsd.so,
reason: /usr/local/bin/system/players/dvdplayer/avcodec-53-x86_64-freebsd.so:
Undefined symbol "ff_h264dsp_init_x86"

ERROR: Unable to load
/usr/local/lib/plexhometheater/system/players/dvdplayer/avcodec-53-x86-freebsd.so,
reason: /usr/local/bin/system/players/dvdplayer/avcodec-53-x86_64-freebsd.so:
Undefined symbol "ff_mlp_init_x86"

This is similar to PR181964 filed previously for multimedia/gstreamer-ffmpeg
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=181964

This issue is caused as during port build some variables not defined in
MAKE_ENV/MAKE_ARGS are leaked to do-build target via .MAKEFLAGS rule in
bsd.port.mk. According to make(1) man page variable assignments in MAKEFLAGS
are treated as those on command line which means they override assignments in
Makefiles.

Unfortunately, this breaks building arch-specific code for libavcodec as
$(ARCH) in config.mak is no longer honored.

Fix: Rename the variable from ARCH to FFMPEG_ARCH, as is done in
multimedia/ffmpeg.

---

Add binutils as builddep on FreeBSD8 and use cmake compiler in ffmpeg configure

---

Plexhometheater will fail to build from ports if ffmpeg is already installed on
the system (via ports or package).

---

Plexhometheater crashes at launch with:
ERROR: Unable to create application. Exiting
Segmentation fault (core dumped)

FROM LOGS:
ERROR: Unable to load /usr/local/bin/system/libcpluff-x86_64-freebsd.so,
reason: Cannot open "/usr/local/bin/system/libcpluff-x86_64-freebsd.so

PR:		193547, 193282, 193190, 193189, 193188
Submitted by:	Ben Woods (maintainer)