textproc/kf5-sonnet: unbreak with hunspell 1.5
-- Could NOT find HUNSPELL (missing:  HUNSPELL_LIBRARIES)
[...]
-- The following OPTIONAL packages have not been found:
 * HUNSPELL , Spell checking support via Hunspell , <http://hunspell.sourceforge.net/>
[...]
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%QT_PLUGINDIR%%/kf5/sonnet/hunspell.so

PR:		214837
Approved by:	portmgr blanket