Unbreak the build with LDAP option selected (for some reason, the problem does not occur on FreeBSD 11.3 and 12.0):
  ld: error: .../libmu_auth.so: undefined reference to ber_memfree
  ld: error: .../libmu_auth.so: undefined reference to ber_memvfree
  ld: error: .../libmu_auth.so: undefined reference to ber_set_option

It looks like an underlinking case, but I do not possess enough of domain
knowledge to properly describe what had changed in our linker and why it
was not a problem before.

Reported by:	maintainer