Prep-work for Qt 5.15
An ambiguous constructor for QSplashScreen has appeared in Qt 5.14,
so previous uses of NULL / nullptr now cause a compile error like

src/gui/src/SplashScreen.cpp:35:4: error: call to constructor of 'QSplashScreen' is ambiguous
 : QSplashScreen( NULL )
   ^              ~~~~
/usr/local/include/qt5/QtWidgets/qsplashscreen.h:58:5: note: candidate constructor
    QSplashScreen(QScreen *screen, const QPixmap &pixmap = QPixmap(), Qt::WindowFlags f = Qt::WindowFlags());
/usr/local/include/qt5/QtWidgets/qsplashscreen.h:61:5: note: candidate constructor
    QSplashScreen(QWidget *parent, const QPixmap &pixmap = QPixmap(), Qt::WindowFlags f = Qt::WindowFlags());

This patch just explicitly casts to the right type of nullptr.
Mentioned in an issue upstream as well.

Not bumping PORTREVISION since this doesn't affect the built code at all
and it will get rebuilt when Qt 5.15 lands anyway.