ftp/curl: Add NTLM option (Fix OpenSSL build w/o DES)
curl fails to build when OpenSSL is built without DES support, with many
"use of undeclared identifier" errors. For example:

curl_ntlm_core.c:392:3: error: use of undeclared identifier 'DES_key_schedule'
  DES_key_schedule ks;
  ^

An issue was reported back in 2015 [1], requesting support for ./configure
detecting OPENSSL_NO_DES, but the issue was ultimately closed:

"We just don't support very custom OpenSSL builds. I could be talked into
accepting patches that introduce support for this however".

Accordingly and leui of an upstream configure patch, this change adds an
NTLM option, enabled by default, and when disabled, defines
CURL_DISABLE_NTLM, which prevents #define'ing USE_NTLM in
WRKSRC/lib/curl_setup.h, resulting in a successful build.

This allows users the opportunity to easily disable the DES requiring
functionality in curl, if they happen to run custom or stripped down
OpenSSL builds.

Note: This issue may impact builds with other SSL libraries that allow
disabling DES, but I did not investigate this question.

[1] https://sourceforge.net/p/curl/bugs/1439/
[2] Would require a version update, which granted, is mostly bugfixes

Reviewed by:	sunpoet (maintainer)
Approved by:	sunpoet (maintainer)
MFH:		No [2]
Differential Revision: D22498