databases/pg_citus: fix build on GCC architectures
C11 compiler is required:
/usr/local/include/postgresql/server/fmgr.h:38: error: previous declaration of 'FunctionCallInfo' was here

Approved by:	mentors (implicit approval)