devel/py-osprofiler: Add missing dependency
osprofiler requires pbr>=1.8 at build time, and fails with the following
error at configure time when it is not available:

  distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.8')

Reported by:	poudriere: pbr reverse dependents bulk (exp) run
Approved by:	portmgr (blanket(s): missing dependencies, build fix)
MFH:		2019Q2


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@505006 35697150-7ecd-e111-bb59-0022644237b5