multimedia/vapoursynth: unbreak runtime on non-x86
vapoursynth.Error: Failed to obtain VapourSynth API pointer. System
does not support SSE2 or is the Python module and loaded core library
mismatched?