games/openmw: fix build with GCC-based architectures
After mygui upgrade, a couple of include <memory> are needed to build with GCC.

Errors:
/wrkdirs/usr/ports/games/openmw/work/openmw-openmw-0.45.0/apps/openmw/mwgui/alchemywindow.hpp:78:14: error: 'unique_ptr' in namespace 'std' does not name a template type

  std::unique_ptr<MWMechanics::Alchemy> mAlchemy;
       ^~~~~~~~~~

/wrkdirs/usr/ports/games/openmw/work/openmw-openmw-0.45.0/apps/openmw/mwgui/alchemywindow.hpp:78:9: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to
+'#include <memory>'?
/wrkdirs/usr/ports/games/openmw/work/openmw-openmw-0.45.0/apps/openmw/mwgui/alchemywindow.hpp:14:1:
+#include <memory>

PR:		237773
Approved by:	tobik (maintainer), mat (mentor)
Differential Revision:	https://reviews.freebsd.org/D20184