sysutils/fusefs-smbnetfs: fix build with GCC-based architectures
This port requires USES=compiler:c11 and including strings.h in one source file to build on GCC architectures.
event.o:(.text+0x838): undefined reference to `g_atomic_int_get'
event.o:(.text+0x9c4): undefined reference to `g_atomic_int_get'
event.o:(.text+0x9dc): undefined reference to `g_atomic_int_set'

PR:		237221
Approved by:	mi@ALDAN.algebra.com (maintainer timeout), mat (mentor)
Differential Revision:	https://reviews.freebsd.org/D20108