games/netherearth: Fix build with Clang 6
bullet.cpp:184:7: error: non-constant-expression cannot be narrowed from type 'double' to 'float' in initializer list [-Wc++11-narrowing]
                                  bullet->pos.x,bullet->pos.y,0.3,1};
                                  ^~~~~~~~~~~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475964_s336959/logs/errors/netherearth-0.51_9.log

- While here add missing dependencies