x11-themes/qtcurve: fix build with GCC-based architectures
GCC9 requires upstream fix because of:
/wrkdirs/usr/ports/x11-themes/qtcurve-gtk2/work/qtcurve-a1ec5f8/.cmake_utils_base/cmake_c_macros/include_fix/qtcurve-utils/gtkprops.h:80:24: error: a reinterpret_cast is not a constant expression
   80 |                 return (GObject*)qtcContainerOf(p, Props, name)->m_w;   \
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/wrkdirs/usr/ports/x11-themes/qtcurve-gtk2/work/qtcurve-a1ec5f8/.cmake_utils_base/cmake_c_macros/include_fix/qtcurve-utils/gtkprops.h:161:9: note: in expansion of macro 'DEF_WIDGET_SIG_CONN_PROPS'

PR:		239622
Approved by:	jhale (maintainer timeout), tcberner (mentor)
Differential Revision:	https://reviews.freebsd.org/D21993