kdevplatform: Add a patch I landed upstream to fix parallel build errors.
From the commit message:
n
  filetemplates plugin: Make testfiletemplates depend on kdevfiletemplates

  There is currently no dependency between both targets, however some of
  the files built by both testfiletemplates and kdevfiletemplates (such as
  classidentifierpage.cpp) depend on ui files that only the latter target
  generates. This means that if one does make testfiletemplates the build
  fails like this:

    /tmp/kdevplatform/plugins/filetemplates/classidentifierpage.cpp:23:25:
    fatal error: ui_newclass.h: No such file or directory