databases/libzdb: fix build on GCC architectures
r529335 partially reverted r499489, which caused another breakage on GCC architectures by passing -L/usr/lib while using GCC from ports and making it link to base libstdc++:
/usr/local/bin/ld: zdbpp.cpp:(.text.startup+0x1f0): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'

Apply changes to Makefile from r499489 to fix it.

PR:		237200


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@529975 35697150-7ecd-e111-bb59-0022644237b5