mail/aerc: Unbreak on arm64
# git.sr.ht/~sircmpwn/pty
vendor/git.sr.ht/~sircmpwn/pty/pty_freebsd.go:50:20: undefined: fiodgnameArg
vendor/git.sr.ht/~sircmpwn/pty/pty_freebsd.go:63:12: undefined: _C_SPECNAMELEN
vendor/git.sr.ht/~sircmpwn/pty/pty_freebsd.go:66:9: undefined: fiodgnameArg
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/ztypes_freebsd_arm64.go:400:12: undefined: uint128

http://thunderx1.nyi.freebsd.org/data/head-arm64-default/p518178_s355024/logs/errors/aerc-0.3.0.log

Unbreak by updating golang.org/x/sys to 33540a1f6037 which adds
support for FreeBSD arm64 and generating the missing
git.sr.ht/~sircmpwn/pty/ztypes_freebsd_arm64.go.

PR:		242312