Fix build when selected SSL library is linked to libthr
When a non-default SSL library is used (GnuTLS, OpenSSL or LibreSSL from
ports) and if it is linked to libthr, compilation fails with the following
error :

/usr/bin/ld: undefined reference to symbol `pthread_mutexattr_gettype@@FBSD_1.0' (try adding -lthr)
//lib/libthr.so.3: could not read symbols: Bad value

As OpenSSL-like ports (OpenSSL from base, OpenSSL and OpenSSL-devel from ports,
LibreSSL and LibreSSL-devel from ports) may or may not be linked to libthr, fix
build by detecting if the selected library is linked to libthr or not.

PR:		230813
Submitted by:	Pascal Christen <pascal.christen@hostpoint.ch>