math/libqalculate: unbreak with ICU 63
In file included from Calculator.cc:45:
In file included from /usr/local/include/unicode/ucasemap.h:25:
/usr/local/include/unicode/localpointer.h:221:40: error: expected ';' at end of declaration list
    LocalPointer(LocalPointer<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                       ^
/usr/local/include/unicode/localpointer.h:366:36: error: expected ';' at end of declaration list
    LocalArray(LocalArray<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                   ^
In file included from Calculator.cc:45:
/usr/local/include/unicode/ucasemap.h:96:1: error: expected ';' at end of declaration list
U_DEFINE_LOCAL_OPEN_POINTER(LocalUCaseMapPointer, UCaseMap, ucasemap_close);
^
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^

Regressed by:	https://github.com/unicode-org/icu/commit/35ce5296c1d3
PR:		232300
Reported by:	antoine (via exp-run)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@482451 35697150-7ecd-e111-bb59-0022644237b5