games/diameter: fix build on GCC architectures
C++11 compiler is required:
res/3dsloader.cpp:77: error: 'nullptr' was not declared in this scope

Approved by:	mentors (implicit approval)