lang/rust: Add manifest-rustfmt-preview to PLIST
This wasn't reported by a simple `poudriere bulk`, but a `poudriere
testport` revealed the problem:

    ====> Running Q/A tests (stage-qa)
    Error: 'lib/rustlib/manifest-rustfmt-preview' is referring to /wrkdirs/usr/ports/lang/rust/work/stage
    Warning: 'bin/rustfmt' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
    ...
    ===> Checking for items in STAGEDIR missing from pkg-plist
    Error: Orphaned: bin/rustfmt
    Error: Orphaned: lib/rustlib/manifest-rustfmt-preview

PR:		225445
Reported by:	jbeich@


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@459943 35697150-7ecd-e111-bb59-0022644237b5