Fix PLIST issue (r524152) with DOCS enabled
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: %%DOCSDIR%%/README.txt
Error: Missing: %%DOCSDIR%%/example/client.c
Error: Missing: %%DOCSDIR%%/example/echoclient.c
Error: Missing: %%DOCSDIR%%/example/echoserver.c
Error: Missing: %%DOCSDIR%%/example/sctp-client-dtls.c
Error: Missing: %%DOCSDIR%%/example/sctp-client.c
Error: Missing: %%DOCSDIR%%/example/sctp-server-dtls.c
Error: Missing: %%DOCSDIR%%/example/sctp-server.c
Error: Missing: %%DOCSDIR%%/example/server.c
Error: Missing: %%DOCSDIR%%/example/tls_bench.c
Error: Missing: %%DOCSDIR%%/taoCert.txt
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/security/wolfssl
=>> Error: check-plist failures detected

Approved by:	portmgr (blanket)