net/remmina-plugin-www: fix build on GCC architectures
This port now requires C11 to build:
/usr/local/include/webkitgtk-4.0/jsc/JSCClass.h:37: error: redefinition of typedef 'JSCClass'
/usr/local/include/webkitgtk-4.0/jsc/JSCValue.h:43: error: previous declaration of 'JSCClass' was here
/usr/local/include/webkitgtk-4.0/jsc/JSCClass.h:40: error: redefinition of typedef 'JSCContext'
/usr/local/include/webkitgtk-4.0/jsc/JSCValue.h:44: error: previous declaration of 'JSCContext' was here

Approved by:	mentors (implicit approval)