shells/ion: Unbreak build with Rust 1.40.0 (D22843)
error[E0503]: cannot use `self.key_bindings` because it was mutably borrowed
  --> /wrkdirs/usr/ports/shells/ion/work/ion-a8872014dbce730ccd00aaa722397dc394a52bf4-a8872014dbce730ccd00aaa722397dc394a52bf4/cargo-crates/liner-0.4.4/src/context.rs:98:17
   |
96 |             let ed = try!(Editor::new_with_init_buffer(stdout, prompt, self, buffer));
   |                                                                        ---- borrow of `*self` occurs here
97 |             match self.key_bindings {
98 |                 KeyBindings::Emacs => Self::handle_keys(keymap::Emacs::new(ed), handler),
   |                 ^^^^^^^^^^^^^^^^^^ use of borrowed `*self`
99 |                 KeyBindings::Vi => Self::handle_keys(keymap::Vi::new(ed), handler),
   |                                                                      -- borrow later used here

error: aborting due to previous error