math/sc-im: fix build on GCC architectures
libxlsxwriter requires newer compiler:
/usr/local/include/xlsxwriter/workbook.h:909: error: wrong number of arguments specified for 'deprecated' attribute