graphics/py-cairo: fix build with GCC architectures
New GCC is required on GCC architectures:
cairo/surface.c:478: error: #pragma GCC diagnostic not allowed inside functions

Approved by:	mentors (implicit approval)