security/py-pyaxo: Add missing dependency
net-im/py-unmessage currently fails at run-time with the following error:

  File "/usr/local/lib/python2.7/site-packages/unmessage/cli.py", line 9, in <module>
    from pyaxo import b2a
  File "/usr/local/lib/python2.7/site-packages/pyaxo.py", line 27, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

This change adds the appropriate and missing dependency on
databases/py-sqlite3.

While I'm here:

 - Verbosify pytest output (one test per line) and print skipped reasons,
   which can be very useful during QA.
 - Pet portlint (extra item in USES/USE_x section: "NO_ARCH".)

Reported by:	DanDare (via IRC, via net-im/py-unmessage)
Approved by:	portmgr (blanket(s): missing dependencies, ports compliance)
MFH:		2019Q3