Restrict to python 3.x due to failure building under 2.7:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 50
    raise ImportError("numpy is required at installation") from e
                                                              ^
  SyntaxError: invalid syntax

Nothing depends on the py27 flavor.

Approved by:	portmgr ("just fix it")


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@547857 35697150-7ecd-e111-bb59-0022644237b5