- Mark BROKEN on 9.x:
src/Tools.cpp:204: error: 'snprintf' is not a member of 'std'

- Switch to options helpers
- Switch to new test framework

Approved by:	portmgr blanket