games/keeperrl: unbreak with GCC
On WITHOUT_CLANG_IS_CC architectures:
g++7 -x c++-header stdafx.h -MMD -O2 -pipe  -fstack-protector -Wl,-rpath=/usr/local/lib/gcc7 -isystem /usr/local/include -fno-strict-aliasing -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-shift-count-overflow -Wno-tautological-constant-out-of-range-compare -Wno-mismatched-tags -ftemplate-depth=512 -DDATA_DIR=\"/usr/local/share/keeperrl\" -DRELEASE -I. -I./extern -o obj/stdafx.h.gch
stdafx.h:16:9: warning: #pragma once in main file
 #pragma once
         ^~~~
cc1plus: warning: unrecognized command line option '-Wno-mismatched-tags'
cc1plus: warning: unrecognized command line option '-Wno-tautological-constant-out-of-range-compare'
/usr/lib/crt1.o: In function `_start1':
/usr/src/lib/csu/powerpc64/crt1.c:(.text+0x156): undefined reference to `main'
collect2: error: ld returned 1 exit status

On DragonFly (in-base GCC 5.4.1):
c++ -MMD -pipe -O2 -isystem /usr/local/include -fno-strict-aliasing -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-shift-count-overflow -Wno-tautological-constant-out-of-range-compare -Wno-mismatched-tags -ftemplate-depth=512 -DDATA_DIR=\"/usr/local/share/keeperrl\" -DRELEASE -I. -I./extern -include-pch obj/stdafx.h.gch -c attr_type.cpp -o obj/attr_type.o
cc1plus: fatal error: -pch: No such file or directory
compilation terminated.