www/py-django-appmedia: convert to USES=python
- convert to USES=python
- limit python version to 2.x:
  """
  File "/usr/local/lib/python3.4/site-packages/appmedia/views.py", line 67
    print osp.join(media_dir, path)
            ^
  SyntaxError: invalid syntax
  """

Approved by:	portmgr (blanket)