archivers/libcabinet: Unbreak build on recent CURRENT
c++  -O2 -pipe -fstack-protector -fno-strict-aliasing   -Wno-deprecated  -std=c++11 -Wno-c++11-extensions  -c bstring.cpp -o bstring.o
In file included from bstring.cpp:16:
./bstring.h:59:40: error: use of undeclared identifier 'strlwr'; did you mean 'strlen'?
                b_string& StrLwr() { if(str != NULL) strlwr(str); return *this; }
                                                     ^~~~~~
                                                     strlen

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p499421_s346424/logs/errors/libcabinet-0.30_2.log

This is caused by having a CXXSTD with default value of c++11 in
bsd.sys.mk now.  Set CXXSTD to gnu++98 explicitly.