Fix build with clang 6 and bump PORTREVISION since the code was wrong in any case
src/dialogs/setupdisplay.cpp:567:41: error: reference to type 'const KFontChooser::DisplayFlags' (aka 'const QFlags<KFontChooser::DisplayFlag>') could not bind to an rvalue of type 'bool'
        if ( KFontDialog::getFont( item->font, false, view() ) == QDialog::Accepted ) {
                                               ^~~~~
/usr/local/include/kde4/kfontdialog.h:134:57: note: passing argument to parameter 'flags' here
                      const KFontChooser::DisplayFlags& flags =
                                                        ^

Reported by:	pkg-fallout