devel/breakpad: require C++11 toolchain (on powerpc*, mips*, sparc*)
checking whether /nxb-bin/usr/bin/c++ supports C++11 features by default... no
checking whether /nxb-bin/usr/bin/c++ supports C++11 features with -std=c++11... no
checking whether /nxb-bin/usr/bin/c++ supports C++11 features with -std=c++0x... no
checking whether /nxb-bin/usr/bin/c++ supports C++11 features with +std=c++11... no
checking whether /nxb-bin/usr/bin/c++ supports C++11 features with -h std=c++11... no
configure: error: *** A compiler with support for C++11 language features is required.

In file included from src/processor/basic_code_modules.cc:46:
./src/processor/range_map-inl.h:132:14: error: no matching member function for call to 'erase'
        map_.erase(iterator_high);
        ~~~~~^~~~~
./src/processor/range_map-inl.h:64:10: note: in instantiation of member function
      'google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::StoreRangeInternal' requested here
  return StoreRangeInternal(base, 0 /* delta */, size, entry);
         ^
src/processor/basic_code_modules.cc:71:15: note: in instantiation of member function
      'google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::StoreRange' requested here
    if (!map_.StoreRange(module->base_address(), module->size(), module)) {
              ^
/usr/include/c++/4.2/bits/stl_map.h:453:7: note: candidate function not viable: no known conversion
      from 'google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::MapConstIterator' (aka '_Rb_tree_const_iterator<std::pair<const
      unsigned long, google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::Range> >') to 'std::map<unsigned long,
      google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::Range, std::less<unsigned long>, std::allocator<std::pair<const
      unsigned long, google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::Range> > >::iterator' (aka '_Rb_tree_iterator<std::pair<const
      unsigned long, google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::Range> >') for 1st argument
      erase(iterator __position)
      ^
/usr/include/c++/4.2/bits/stl_map.h:468:7: note: candidate function not viable: no known conversion
      from 'google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::MapConstIterator' (aka '_Rb_tree_const_iterator<std::pair<const
      unsigned long, google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::Range> >') to 'const std::map<unsigned long,
      google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::Range, std::less<unsigned long>, std::allocator<std::pair<const
      unsigned long, google_breakpad::RangeMap<unsigned long, google_breakpad::linked_ptr<const
      google_breakpad::CodeModule> >::Range> > >::key_type' (aka 'const unsigned long') for 1st
      argument
      erase(const key_type& __x)
      ^
/usr/include/c++/4.2/bits/stl_map.h:483:7: note: candidate function not viable: requires 2 arguments,
      but 1 was provided
      erase(iterator __first, iterator __last)
      ^
1 error generated.

Reported by:	pkg-fallout (mips64)