Mark BROKEN: missing header
libtool: compile:  cc -DHAVE_CONFIG_H -I. -I../.. -I../../include -O2 -pipe -fstack-protector -fno-strict-aliasing -c libwebfwlog_udf.c  -fPIC -DPIC -o .libs/libwebfwlog_udf.o
libwebfwlog_udf.c:13:10: fatal error: 'mysql.h' file not found
#include <mysql.h>

Reported by:	pkg-fallout