- Mark BROKEN on 11.x:
(3104) Compiling globe.pas
/wrkdirs/usr/ports/russian/emkatic/work/emkatic-0.28-src/globe.pas(28,67) Fatal: (10022) Can't find unit Serial used by Globe
Fatal: (1018) Compilation aborted
Error: /usr/local/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile Project, Mode: SrcDist, Target: emkatic: stopped with exit code 256
ERROR: failed compiling of project /wrkdirs/usr/ports/russian/emkatic/work/emkatic-0.28-src/emkatic.lpi

- Switch to options helpers

Approved by:	portmgr blanket