MFH: r448303
net/py-pcs: Limit to Python 2.7 (Does not support Python 3)

This version (0.6) of the upstream package version does not appear to intend to,
or explicitly support Python 3. It also currently fails to build with Python 3.x
with a SyntaxError:

  SyntaxError: Missing parentheses in call to 'print'

This change limits the USES=python:<version-spec> support declaration to 2.7
accordingly.

Note: A closed upstream PR [1] mentions fixing tests for Python 3 in 2015, so
the version-specifier may change (be relaxed) upon future port/version updates,
or at MAINTAINER's (also the package author) discretion to explicitly mark
Python 3 as an intended supported version, *independent* to any build/run-time
issues that may exist.

While I'm here, pet portlint:

- Strip shared libraries
- Add LICENSE_FILE
- Fix section order (*_DEPENDS)

[1] https://github.com/gvnn3/PCS/pull/2

PR:		219325
Reported by:	Johannes Jost Meixner
Approved by:	portmgr (blanket)

Approved by:	ports-secteam (blanket)