audio/libgroove: unbreak build with ffmpeg 3.x
groove/encoder.c:84:19: error:
      'avcodec_encode_audio2' is deprecated [-Werror,-Wdeprecated-declarations]
    int errcode = avcodec_encode_audio2(e->stream->codec, &e->pkt, frame, &got_packet);
                  ^
/usr/local/include/libavcodec/avcodec.h:5283:5: note: 'avcodec_encode_audio2' has been explicitly
      marked deprecated here
int avcodec_encode_audio2(AVCodecContext *avctx, AVPacket *avpkt,
    ^
groove/encoder.c:84:52: error: 'codec'
      is deprecated [-Werror,-Wdeprecated-declarations]
    int errcode = avcodec_encode_audio2(e->stream->codec, &e->pkt, frame, &got_packet);
                                                   ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated
      here
    AVCodecContext *codec;
                    ^
groove/encoder.c:94:5: error:
      'av_free_packet' is deprecated [-Werror,-Wdeprecated-declarations]
    av_free_packet(&e->pkt);
    ^
/usr/local/include/libavcodec/avcodec.h:4472:6: note: 'av_free_packet' has been explicitly marked
      deprecated here
void av_free_packet(AVPacket *pkt);
     ^
groove/encoder.c:101:34: error:
      'codec' is deprecated [-Werror,-Wdeprecated-declarations]
        avcodec_close(e->stream->codec);
                                 ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated
      here
    AVCodecContext *codec;
                    ^
groove/encoder.c:134:44: error:
      'codec' is deprecated [-Werror,-Wdeprecated-declarations]
    AVCodecContext *codec_ctx = e->stream->codec;
                                           ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated
      here
    AVCodecContext *codec;
                    ^
groove/encoder.c:148:16: error:
      'codec' is deprecated [-Werror,-Wdeprecated-declarations]
    e->stream->codec = codec_ctx;
               ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated
      here
    AVCodecContext *codec;
                    ^
groove/encoder.c:620:24: error:
      'codec' is deprecated [-Werror,-Wdeprecated-declarations]
        0 : e->stream->codec->frame_size;
                       ^
/usr/local/include/libavformat/avformat.h:893:21: note: 'codec' has been explicitly marked deprecated
      here
    AVCodecContext *codec;
                    ^
7 errors generated.

PR:		207547