net/ulxmlrpcpp: fix build on GCC architectures
Use new GCC because of:
ulxr_value.cpp:895: error: 'snprintf' is not a member of 'std'

Also add include cstring because of:
ulxr_ssl_connection.cpp: In function 'int ulxr::password_cb(char*, int, int, void*)':
ulxr_ssl_connection.cpp:63:3: error: 'strcpy' was not declared in this scope

63 |   strcpy(buf, pass.c_str());
   |   ^~~~~~

Approved by:	linimon (mentor)
Differential Revision:	https://reviews.freebsd.org/D21720