devel/arachne-pnr: fix build with GCC-based architectures
Building with GCC9 fails with:
src/util.hh: In instantiation of ‘std::set<typename M::key_type> keys(const M&) [with M = std::map<CBit, bool>; typename M::key_type = CBit]’:
src/chipdb.cc:73:23:   required from here
src/util.hh:191:24: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
  191 |   return std::move(keys);
      |                        ^
src/util.hh:191:24: note: remove ‘std::move’ call

As reported at https://github.com/YosysHQ/arachne-pnr/issues/134

Add -Wno-error=pessimizing-move to CFLAGS for GCC build.

PR:		240256
Approved by:	linimon (mentor), jsorocil@gmail.com (maintainer timeout)