textproc/ibus-qt: unbreak with ICU 63 on FreeBSD < 11.2
In file included from qtim/ibus-input-context.cpp:43:
In file included from /usr/local/include/unicode/unorm.h:25:
In file included from /usr/local/include/unicode/unorm2.h:34:
/usr/local/include/unicode/localpointer.h:221:34: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    LocalPointer(LocalPointer<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                 ^
/usr/local/include/unicode/localpointer.h:221:40: error: expected ';' at end of declaration list
    LocalPointer(LocalPointer<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                       ^
                                       ;
/usr/local/include/unicode/localpointer.h:366:30: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    LocalArray(LocalArray<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                             ^
/usr/local/include/unicode/localpointer.h:366:36: error: expected ';' at end of declaration list
    LocalArray(LocalArray<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                   ^
                                   ;
In file included from qtim/ibus-input-context.cpp:43:
In file included from /usr/local/include/unicode/unorm.h:25:
In file included from /usr/local/include/unicode/unorm2.h:36:
/usr/local/include/unicode/uset.h:330:1: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
^
/usr/local/include/unicode/localpointer.h:493:53: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                    ^
In file included from qtim/ibus-input-context.cpp:43:
In file included from /usr/local/include/unicode/unorm.h:25:
In file included from /usr/local/include/unicode/unorm2.h:36:
/usr/local/include/unicode/uset.h:330:1: error: expected ';' at end of declaration list
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
In file included from qtim/ibus-input-context.cpp:43:
In file included from /usr/local/include/unicode/unorm.h:25:
/usr/local/include/unicode/unorm2.h:261:1: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
U_DEFINE_LOCAL_OPEN_POINTER(LocalUNormalizer2Pointer, UNormalizer2, unorm2_close);
^
/usr/local/include/unicode/localpointer.h:493:53: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                    ^
In file included from qtim/ibus-input-context.cpp:43:
In file included from /usr/local/include/unicode/unorm.h:25:
/usr/local/include/unicode/unorm2.h:261:1: error: expected ';' at end of declaration list
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
qtim/ibus-input-context.cpp:540:13: warning: 'unorm_normalize' is deprecated [-Wdeprecated-declarations]
        i = unorm_normalize (combination_buffer, m_n_compose, UNORM_NFC, 0, result, IBUS_MAX_COMPOSE_LEN + 1, &state);
            ^
/usr/local/include/unicode/unorm.h:214:1: note: 'unorm_normalize' declared here
unorm_normalize(const UChar *source, int32_t sourceLength,
^

Regressed by:	https://github.com/unicode-org/icu/commit/35ce5296c1d3
PR:		232300
Reported by:	antoine (via exp-run)