MFH: devel/py-buildbot{-*}: Update to 2.2.0 (r500101 r500102 r500578)
buildbot:

  - Now python 3 only (3.5+)
  - Add missing tests_requires to setup.py

buildbot-worker:

  - Retains Python 2/3 compatibility
  - Remove setup.py patch (upstreamed)

Changelog:

  https://docs.buildbot.net/current/relnotes/index.html#buildbot-2-2-0-2019-04-07

Security:	5536ea5f-6814-11e9-a8f7-0050562a4d7b

Unbreak

devel/py-buildbot-*: Limit to Python 3.5+

These packages only support Python 3.x [1], currently failing to build:

  File "/usr/local/lib/python2.7/site-packages/buildbot_pkg.py", line 254, in run
    super().run()
TypeError: super() takes at least 1 argument (0 given)

antoine@ fixed fallout in py-buildbot-www in ports r500102

[1] https://github.com/buildbot/buildbot/commit/403722c20e7f96707be3d15db54b25f472b8a525

Reported by:	pkg-fallout

Approved by:	ports-secteam (joneum (r500101), blanket: build fix)