databases/percona55-server: fix build
Requires C11 features:
/wrkdirs/usr/ports/databases/percona55-server/work/percona-server-5.5.61-38.13/storage/innobase/include/os0sync.h:386:4: error: #error "Unsupported platform"

Approved by:	mentors (implicit approval)