Fix build error on archs where 'unsigned long' is 32bit (tested on i386): Source/Core/Core/NetPlayClient.cpp:1218:12: error: invalid operands to binary expression ('sf::Packet' and 'unsigned long')
Ask lzo/lzodefs.h to prefer 'unsigned int' for type lzo_uint32_t
(lzo_uint32e_t) over 'unsigned long int' because SFML's Packet& operator >>()
cannot handle 'unsigned long int' as argument (see SFML/Network/Packet.hpp).
It can accept a Uint32 reference, which is defined as an 'unsigned int'
reference via SFML/Config.hpp.

Also, set forgotten requirement for c++17-lang.