- Fix link pointing to STAGEDIR after install, this fixes runtime error:
/jline.jar:/usr/local/share/java/classes/zookeeper.jar:
org.apache.zookeeper.server.quorum.QuorumPeerMain
/usr/local/etc/zookeeper/zoo.cfg"'
Error: Could not find or load main class
org.apache.zookeeper.server.quorum.QuorumPeerMain

- Add NO_ARCH
- There's no need to include bsd.port.pre.mk
- Use options helper
- Remove deprecated @dirrmtry from pkg-plist

PR:		206739
Submitted by:	myself
Approved by:	maintainer
MFH:		2016Q1