multimedia/gstreamer1-validate: fix build on GCC architectures
C11 compiler is required:
gstvalidateflow.c:84: error: redefinition of typedef 'ValidateFlowOverride'
gstvalidateflow.c:72: error: previous declaration of 'ValidateFlowOverride' was here