net-mgmt/openbmp: fix build with GCC architectures
Building with GCC requires include sys/types.h in Server/src/Logger.h.

/wrkdirs/usr/ports/net-mgmt/openbmp/work/openbmp-0.14.0/Server/src/Logger.h:99:27: error: 'u_char' has not been declared
     void setWidthFunction(u_char width);

PR:		239329
Approved by:	pizzamig (maintainer), linimon (mentor)
Differential Revision:	https://reviews.freebsd.org/D21026


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@507636 35697150-7ecd-e111-bb59-0022644237b5