math/asymptote: fix plist
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/info/asy-faq.info


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@514888 35697150-7ecd-e111-bb59-0022644237b5