x11-wm/sway: bump required wlroots version after r491073
../sway/server.c:7:10: fatal error: 'wlr/backend/noop.h' file not found
 #include <wlr/backend/noop.h>
          ^~~~~~~~~~~~~~~~~~~~


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@491087 35697150-7ecd-e111-bb59-0022644237b5