devel/py-cbor2: Remove Python 3 support restriction
This package supports Python 3.x support, so allow it accordingly. It is
required for an upcoming www/py-autobahn update (Python 2/3 compatible).

During QA, a UnicodeDecodeError was observed running tests under Python 3:

File "/usr/local/lib/python3.6/site-packages/py/_vendored_packages/iniconfig.py", line 82, in _parse
  for lineno, line in enumerate(line_iter):
File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
  return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 165: ordinal not in range(128)

pytest uses the py package, which vendors the iniconfig package, which
isn't unicode aware [1][2][3]. Patch out unicode characters from setup.cfg
accordingly until it's resolved.

While investigating the cause of the above issue, a fix for setup.cfg's
encoding was identified, which removes the need to set the locale via
USE_LOCALE so remove it accordingly.

While I'm here:

  - Pet portlint, spurious space at end of line in pkg-descr
  - Add LICENSE_FILE/TEST_DEPENDS/test target/NO_ARCH

[1] https://github.com/pytest-dev/pytest/issues/3799
[2] https://github.com/RonnyPfannschmidt/iniconfig/issues/5
[3] https://github.com/RonnyPfannschmidt/iniconfig/issues/4

portlint: OK (looks fine.)
porttest: OK (poudriere: 12amd64{py36,py27})
maketest: 215 passed, 1 skipped in 3.29 seconds (Python 2.7)
maketest: 209 passed, 7 skipped in 3.07 seconds (Python 3.6)

Approved by:	portmgr (blanket: ports/framework compliance)
MFH:		2019Q2