textproc/docbook-xls-ns: Fix stage QA
Fix this error:
  ===> Checking for items in STAGEDIR missing from pkg-plist
  Error: Orphaned: share/xsl/docbook-ns/svn-commit.tmp

No revbump is necessary because the extra file is unwanted and
wasn't packaged.  This allows stage QA checks to pass

approved by:	just-fix-it