lang/cint: Unbreak build with GCC 9
G__cpp_list.cxx: In function 'int G__list_49_0_10(G__value*, const char*, G__param*, int)':
G__cpp_list.cxx:707:109: error: 'std::__cxx11::list<int, std::allocator<int> >::iterator' {aka 'struct std::_List_iterator<int>'} has no member named 'operator=='; did you mean 'operator='?
  707 |       G__letint(result7, 103, (long) ((list<int,allocator<int> >::iterator*) G__getstructoffset())->operator==(*(list<int,allocator<int> >::iterator*) libp->para[0].ref));
      |                                                                                                             ^~
      |                                                                                                             operator=
G__cpp_list.cxx: In function 'int G__list_49_0_11(G__value*, const char*, G__param*, int)':
G__cpp_list.cxx:713:109: error: 'std::__cxx11::list<int, std::allocator<int> >::iterator' {aka 'struct std::_List_iterator<int>'} has no member named 'operator!='; did you mean 'operator='?
  713 |       G__letint(result7, 103, (long) ((list<int,allocator<int> >::iterator*) G__getstructoffset())->operator!=(*(list<int,allocator<int> >::iterator*) libp->para[0].ref));
      |                                                                                                             ^~
      |                                                                                                             operator=

http://pb2.nyi.freebsd.org/data/120i386-default-PR238330/2019-06-09_20h27m22s/logs/errors/cint-5.18.00_12.log

While here make the build abort fast on build errors instead of
carrying on like nothing happened.

PR:		238907
Reported by:	antoine (via exp-run in PR 238330)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@505728 35697150-7ecd-e111-bb59-0022644237b5