mail/thunderbird: unbreak with RUST=on
env CARGO_TARGET_DIR=. RUSTC=/usr/local/bin/rustc /usr/local/bin/cargo build --release --frozen --manifest-path /wrkdirs/usr/ports/mail/thunderbird/work/thunderbird-52.3.0/mozilla/toolkit/library/gtest/rust/Cargo.toml --target=x86_64-unknown-freebsd --verbose --
error: failed to load source for a dependency on `mp4parse_capi`

Caused by:
  Unable to update file:///wrkdirs/usr/ports/mail/thunderbird/work/thunderbird-52.3.0/mozilla/media/libstagefright/binding/mp4parse_capi

Caused by:
  failed to parse manifest at `/wrkdirs/usr/ports/mail/thunderbird/work/thunderbird-52.3.0/mozilla/media/libstagefright/binding/mp4parse_capi/Cargo.toml`

Caused by:
  could not parse input as TOML

Caused by:
  duplicate key: `build` for key `package`

cf. https://hg.mozilla.org/releases/mozilla-esr52/shortlog/THUNDERBIRD_52_VERBRANCH

Reported by:	YuryG @ forums.freebsd.org