x11-wm/blackbox: Fix build with Clang 6, Fix TOOLS_ONLY option
Clang 6 (on 12-CURRENT) reports the following error during build:

EWMH.cc:250:7: error: non-constant-expression cannot be narrowed from type
'long' to 'unsigned long' in initializer list [-Wc++11-narrowing]
    { static_cast<long>(x), static_cast<long>(y) };
      ^~~~~~~~~~~~~~~~~~~~

There was also a bug introduced 4 years ago which removed the MAN1 variable a
later INSTALL_MAN macro relied on [1]. This caused a build/install failure
when the TOOLS_ONLY option was enabled.

This change fixes those two issues.

While I'm here level up port compliance:

  - Add LICENSE_FILE
  - Convert to OPTIONS helpers
  - Regenerate patches

[1] http://svnweb.freebsd.org/changeset/ports/346174
[2] https://lists.freebsd.org/pipermail/freebsd-ports/2018-August/114039.html

PR:		226708
Submitted by:	<Trond Endrestol ximalas info> (Clang 6 fix)
Approved by:	Andrew J. Caines <A J Caines halplant com> (technically)
Approved by:	portmgr (implicit, build fixes, framework compliance)
Reported by:	Erich Dollansky <freebsd ed lists sumeritec com> [2]
MFH:		2018Q3