Mark BROKEN: tries to clone git repository during build phase
    Updating git repository `https://github.com/mmokhi/rust-mdns`
warning: spurious network error (2 tries remaining): [12/-1] curl error:
warning: spurious network error (1 tries remaining): [12/-1] curl error:
error: failed to load source for a dependency on `mdns`
Caused by:
  Unable to update https://github.com/mmokhi/rust-mdns
Caused by:
  failed to clone into: /wrkdirs/usr/ports/multimedia/librespot/work/librespot-85dbc3b/git/db/rust-mdns-02ad69c3177fccfb

Reported by:	pkg-fallout