Mark as jobs unsafe
gmake[2]: Entering directory `/wrkdirs/usr/ports/devel/menhir/work/menhir-20080912/src'
Grammar has 30 nonterminal symbols, among which 1 start symbols.
Grammar has 26 terminal symbols.
Fatal error: exception Sys_error("parser.ml: No such file or directory")
Grammar has 82 productions.
Built an LR(0) automaton with 113 states.
Built an LR(1) automaton with 113 states.
5 shift/reduce conflicts were silently solved.
30 out of 113 states are represented.
26 out of 59 symbols keep track of their start position.
21 out of 59 symbols keep track of their end position.
47 out of 113 states have a default reduction.
34 out of 83 productions exploit shiftreduce optimization.
15 out of 113 states can peek at an error.
13 out of 113 states can do error recovery.
The generated parser cannot raise Error.
411 functions before inlining, 103 functions after inlining.
gmake[2]: *** No rule to make target `parser.ml', needed by `parser.cmx'.  Stop.