editors/zoinks: Fix build with Clang 6
TFWCursors.cpp:32:2: error: constant expression evaluates to 128 which cannot be narrowed to type 'char' [-Wc++11-narrowing]
        0x80, 0x00,
        ^~~~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475044_s336572/logs/zoinks-0.4.1_2.log

- While here add missing dependencies and LICENSE_FILE