Add missing dependency on GTK, otherwise installed package fails to run:
  Traceback (most recent call last):
    File "/usr/local/bin/arandr", line 41, in <module>
      from screenlayout.gui import main
    File "/usr/local/lib/python3.7/site-packages/screenlayout/gui.py",
    line 28, in <module>
      gi.require_version('Gtk', '3.0')
    File "/usr/local/lib/python3.7/site-packages/gi/__init__.py",
    line 130, in require_version
      raise ValueError('Namespace %s not available' % namespace)
  ValueError: Namespace Gtk not available

Reported by:	Zeus Panchenko


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@548063 35697150-7ecd-e111-bb59-0022644237b5