Mark broken: Fails to compile
libtool: compile:  c++ -DHAVE_CONFIG_H -I. -I../.. -I../../src -I../../libltdl -I/usr/local/include -I/usr/local/include/synfig-0.0 -I/usr/local/include/libxml++-2.6 -I/usr/local/include/libxml++-2.6/include -I/usr/local/include/libxml2 -I/usr/local/include/glibmm-2.4 -I/usr/local/lib/glibmm-2.4/include -I/usr/local/include/glib-2.0 -I/usr/local/include -I/usr/local/include/sigc++-2.0 -I/usr/local/lib/sigc++-2.0/include -DLOCALEDIR=\"/usr/local/share/locale\" -O2 -pipe -fno-strict-aliasing -DNDEBUG -W -Wall -MT libsynfigapp_la-layerparamdisconnect.lo -MD -MP -MF .deps/libsynfigapp_la-layerparamdisconnect.Tpo -c actions/layerparamdisconnect.cpp  -fPIC -DPIC -o .libs/libsynfigapp_la-layerparamdisconnect.o
actions/layerparamdisconnect.cpp: In member function 'virtual void synfigapp::Action::LayerParamDisconnect::perform()':
actions/layerparamdisconnect.cpp:143: error: 'class etl::handle<synfig::ValueNode>' has no member named 'clone'
gmake[3]: *** [libsynfigapp_la-layerparamdisconnect.lo] Error 1

Reported by:	pkg-fallout since january 2014