games/gnuchess: remove duplicate plist entry
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: share/info/gnuchess.info
===> Error: Plist issues found.

It's already added via INFO.  Thanks to check-plist for providing
misleading error messages.

http://package21.nyi.freebsd.org/data/113amd64-default-qat/532906/logs/gnuchess-6.2.6.log