lang/php74: fix build on GCC architectures
Use C11 compiler because of:
/wrkdirs/usr/ports/lang/php74/work/php-7.4.0RC1/Zend/zend_compile.h:363: error: redefinition of typedef 'zend_property_info'
/wrkdirs/usr/ports/lang/php74/work/php-7.4.0RC1/Zend/zend_types.h:385: error: previous declaration of 'zend_property_info' was here

Disable DTRACE on powerpc64 due to:
dtrace: failed to link script /usr/local/poudriere/ports/default/lang/php74/work/php-7.4.0RC1/Zend/zend_dtrace.d: an error was encountered while processing main/.libs/main.o

PR:		240733
Approved by:	tz (maintainer), linimon (mentor)