devel/git-cinnabar: chase r423921 by updating to 0.4.0.b3.6
common-main.o: In function `main':
common-main.c:(.text+0x0): multiple definition of `main'
cinnabar-helper.o:../cinnabar-helper.c:(.text+0x1b0): first defined here
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Changes:	https://github.com/glandium/git-cinnabar/compare/0.4.0b3...75f38ed
PR:		213417 (for tracking)
Reported by:	pkg-fallout