graphics/libpuzzle: Fixup r496850 and fix build of sysutils/ftwin on CURRENT
It is not puzzle-diff that needs to be linked with libm, but
libpuzzle.

ld: error: /usr/local//lib/libpuzzle.so: undefined reference to round

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p500844_s347134/logs/errors/ftwin-0.8.8_4.log