sysutils/cbsd: fix build on GCC architectures
Linking to C++ libraries compiled by GCC9 requires GCC9:
/wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-12.1.1/misc/src/dump_iscsi_discovery.c:171: undefined reference to `simpleXmlGetLineNumber'
/wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-12.1.1/misc/src/dump_iscsi_discovery.c:205: undefined reference to `simpleXmlGetLineNumber'
/wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-12.1.1/misc/src/dump_iscsi_discovery.c:215: undefined reference to `simpleXmlGetLineNumber'
/wrkdirs/usr/ports/sysutils/cbsd/work/cbsd-12.1.1/misc/src/dump_iscsi_discovery.c:225: undefined reference to `simpleXmlGetLineNumber'

Also, remove -mminimal-toc, not needed with the current version.

Approved by:	mentors (implicit approval), portmgr (removing architecture specific fixes)