Mark broken: Does not compile
error CS1705: Assembly `gdk-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' references `Mono.Cairo, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' which has a higher version number than imported assembly `Mono.Cairo, Version=2.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
./Hyena.Data.Gui/ListView/ListView_Rendering.cs(53,53): error CS0012: The type `Cairo.Context' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Mono.Cairo, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
/usr/local/libdata/pkgconfig/../../lib/mono/gtk-sharp-2.0/gdk-sharp.dll (Location of the symbol related to previous error)

Reported by:	pkg-fallout since august 2013