Fix opencolorio-tools build. Now that opencolorio has a post-patch, opencolorio-tools can't have one.
opencolorio-tools fails stage-qa, though, due to some stray files
in STAGEDIR that are probably simplest to just list as @comment inside
pkg-plist-tools:

===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: include/OpenColorIO/OpenColorABI.h
Error: Orphaned: include/OpenColorIO/OpenColorIO.h
Error: Orphaned: include/OpenColorIO/OpenColorTransforms.h
Error: Orphaned: include/OpenColorIO/OpenColorTypes.h
Error: Orphaned: libdata/pkgconfig/OpenColorIO.pc