MFH: r481437 math/py-graphillion: Update to 1.2
This version fixes build failures on FreeBSD versions that use Clang 6:

src/graphillion/zdd.cc:461:31: error: invalid operands to binary expression ('std::__1::ostream' (aka 'basic_ostream<char>') and 'std::__1::ostream')
  if (out == std::cout || out == std::cerr)
                          ~~~ ^  ~~~~~~~~~

Reported by:	pkg-fallout

Approved by:	ports-secteam (miwi)