multimedia/php-pHash: fix build on GCC architectures
x265 requires C++11 compiler:
/usr/local/lib/libx265.so.179: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'

MFH:		2020Q3 (fix build blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@545108 35697150-7ecd-e111-bb59-0022644237b5