Add a patch to drop CMake calls to QT5_WRAP_CPP().
The USE_QT5 code path already unconditionally sets CMAKE_AUTOMOC to on.

Calling QT5_WRAP_CPP() used to be just redundant, as antimicro_HEADERS_MOC
was never actually added as a source dependency of the antimicro target. In
other words, CMake's own automoc infrastructure was actually being used and
the moc invocations from QT5_WRAP_CPP() were not being made at all.

Starting with Qt 5.9.4, calling QT5_WRAP_CPP() disables the AUTOMOC property
on the macro's input files, which means neither CMake's automoc
infrastructure not QT5_WRAP_CPP()'s code were being used and we ended up
with several 'undefined reference to vtable' errors when linking.

Sent upstream: https://github.com/AntiMicro/antimicro/pull/207

PR:		225436


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@460285 35697150-7ecd-e111-bb59-0022644237b5