games/cube: Unbreak with Clang 6
clients2c.cpp:259:45: error: non-constant-expression cannot be narrowed from type
      'short' to 'float' in initializer list [-Wc++11-narrowing]
            vec v = { ents[i].x, ents[i].y, ents[i].z };
                                            ^~~~~~~~~
clients2c.cpp:352:20: warning: ISO C++11 does not allow conversion from string
      literal to 'char *' [-Wwritable-strings]
            neterr("type");
                   ^

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475044_s336572/logs/cube-2005.08.29_17.log

- Add missing GL dependency