x11-servers/xwayland-devel: unbreak with libglvnd
"pkg-config --cflags gl" no longer contains -I/usr/local/include/libdrm

In file included from ../glx/glxdriswrast.c:39:
/usr/local/include/GL/internal/dri_interface.h:43:10: fatal error: 'drm.h' file not found
 #include <drm.h>
          ^~~~~~~


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@536672 35697150-7ecd-e111-bb59-0022644237b5