sysutils/burp: Fix build with Clang 6
server.c:546:25: error: ordered comparison between pointer and zero ('struct strlist **' and 'int')
                if(!ret && cconf->keep>0)
                           ~~~~~~~~~~~^~

http://beefy12.nyi.freebsd.org/data/head-amd64-default/p475478_s336801/logs/errors/burp-1.4.40_1.log

- Remove bad BROKEN tag (util/bdthreads.cc does not exist in burp)