archivers/py-lz4: Remove pytest-runner from BUILD_DEPENDS
pkg-fallout reports, after setuptools attempts to fetch pytest as a dependency:

distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest<4.0.0,>=3.8.2')

pytest was recently updated to 4.x, which is presumably the root source of the
issue, but I wasn't able to identify the source of the pinned pytest version,
or why the fetch of pytest was attempted.

However, remove pytest-runner from BUILD_DEPENDS as a stop gap, since as
setup.py states:

# Only require pytest-runner if actually running the tests
needs_pytest = {'pytest', 'test', 'ptr'}.intersection(sys.argv)
pytest_runner = ['pytest-runner'] if needs_pytest else []

Further, since the port is using pythonX.Y -m pytest as the test invocation,
rather than pythonX.Y setup.py test, the dependency is spurious anyway.

Reported by: pkg-fallout