Under 11.2:
main.c:182:37: error: variable 'ap' is uninitialized when used here
[-Werror,-Wuninitialized]
    len = vsnprintf(str, size, fmt, ap);
                                    ^~
Initializing this variable breaks under other FreeBSD releases. As users
of FreeBSD 11 are unlikely to use bleeding edge krb5-devel, flag it broken
under FreeBSD 11.

MFH:		2019Q3