MFH: r418337
Add missing dependencies to pass `make stage-qa'.

Error: /usr/local/bin/qtcreator is linked to /usr/local/lib/.mesa/libGL.so from graphics/libGL but it is not declared as a dependency
Warning: you need USE_GL+=gl
Error: /usr/local/lib/qtcreator/plugins/libCore.so is linked to /usr/local/lib/libQt5Help.so.5 from devel/qt5-help but it is not declared as a dependency
Warning: you need USE_QT5+=help
Error: /usr/local/lib/qtcreator/plugins/libCore.so is linked to /usr/local/lib/libQt5PrintSupport.so.5 from print/qt5-printsupport but it is not declared as a dependency
Warning: you need USE_QT5+=printsupport

Approved by:	ports-secteam (junovitch)