Mark BROKEN: fails to stage
(system "cc -pipe  -O0 -Wall -Wwrite-strings -Wmissing-declarations -Wredundant-decls -Wcast-qual -Wno-unused-label -Wno-uninitialized -fstack-protector -fno-strict-aliasing  -fPIC -c -Wall edline.c")
edline.c:22:10: fatal error: 'readline/readline.h' file not found
#include <readline/readline.h>
         ^~~~~~~~~~~~~~~~~~~~~
...
install: /wrkdirs/usr/ports/lang/scm/work/scm/edline.so: No such file or directory

Reported by:	pkg-fallout