devel/android-tools-adb-devel: unbreak build on DragonFly (forgot in r400820)
make(1) suffix rules discard original extension as used by bsd.*.mk
which leads to unpredictable behavior if more than one candidate is
found under ${.PATH}. So, partially qualify pathname to avoid
accidentally building libcutils/sockets.c despite SRCS=sockets.cpp

  $ echo 'void foo() { }' > a.c
  $ echo 'int main() { }' > a.cxx
  $ make PROG_CXX=test SRCS=a.cxx NO_MAN= -f /usr/share/mk/bsd.prog.mk
  cc  -O -pipe    -std=gnu99  -c a.c
  c++  -O -pipe  -o test a.o
  /usr/lib/crt1.o: In function `_start':
  crt1.c:(.text+0x132): undefined reference to `main'
  *** Error code 1

which in adb case leads to (since partial C++ conversion in 6.0.0)

  adb.o: In function `handle_packet(apacket*, atransport*)':
  adb.cpp:(.text+0x2518): undefined reference to `find_local_socket(unsigned int, unsigned int)'
  adb.cpp:(.text+0x2613): undefined reference to `find_local_socket(unsigned int, unsigned int)'
  adb.cpp:(.text+0x276a): undefined reference to `find_local_socket(unsigned int, unsigned int)'
  adb.cpp:(.text+0x2875): undefined reference to `create_local_service_socket(char const*)'
  adb.cpp:(.text+0x288c): undefined reference to `create_remote_socket(unsigned int, atransport*)'
  adb.cpp:(.text+0x2a41): undefined reference to `create_remote_socket(unsigned int, atransport*)'
  adb_listeners.o: In function `listener_event_func(int, unsigned int, void*)':
  adb_listeners.cpp:(.text+0xe2): undefined reference to `create_local_socket(int)'
  adb_listeners.cpp:(.text+0xfe): undefined reference to `connect_to_remote(asocket*, char const*)'
  adb_listeners.o: In function `ss_listener_event_func(int, unsigned int, void*)':
  adb_listeners.cpp:(.text+0x1b1): undefined reference to `create_local_socket(int)'
  adb_listeners.cpp:(.text+0x1be): undefined reference to `connect_to_smartsocket(asocket*)'
  services.o: In function `host_service_to_socket(char const*, char const*)':
  services.cpp:(.text+0x64d): undefined reference to `create_local_socket(int)'
  services.cpp:(.text+0x6b7): undefined reference to `create_local_socket(int)'
  transport.o: In function `input_thread(void*)':
  transport.cpp:(.text+0x1931): undefined reference to `close_all_sockets(atransport*)'
  *** [adb] Error code 1