games/seabattle: Fix build after ncurses update(?)
In file included from binp.c:6:
./batt.h:57:6: error: conflicting types for 'exit_curses'
void exit_curses(void);
     ^
/usr/include/curses.h:2093:29: note: previous declaration is here
extern NCURSES_EXPORT(void) exit_curses (int) GCC_NORETURN;
                            ^
binp.c:45:6: error: conflicting types for 'exit_curses'
void exit_curses(void)                     /* Shutdown curses nicely so the */
     ^