games/odamex: Fix build with Clang 6
common/d_dehacked.cpp:883:16: error: non-constant-expression cannot be narrowed from type 'uintptr_t' (aka 'unsigned int') to 'ptrdiff_t' (aka 'int') in initializer list [-Wc++11-narrowing]
                { "ID #",                               myoffsetof(mobjinfo_t,doomednum) },
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

http://beefy11.nyi.freebsd.org/data/head-i386-default/p475044_s336572/logs/odamex-0.7.0_2.log

- While here add missing libpng dependency so that it doesn't use its own
  bundled version