x11/lxqt-about: add missing translation files
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%LXQT_TRANSLATIONS%%/lxqt-about/lxqt-about_arn.qm
Error: Orphaned: %%LXQT_TRANSLATIONS%%/lxqt-about/lxqt-about_ast.qm
Error: Orphaned: %%LXQT_TRANSLATIONS%%/lxqt-about/lxqt-about_bg.qm
Error: Orphaned: %%LXQT_TRANSLATIONS%%/lxqt-about/lxqt-about_fa.qm
Error: Orphaned: %%LXQT_TRANSLATIONS%%/lxqt-about/lxqt-about_pt_PT.qm
Error: Orphaned: %%LXQT_TRANSLATIONS%%/lxqt-about/lxqt-about_sv.qm

Approved by:	fixit-blanket


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@539809 35697150-7ecd-e111-bb59-0022644237b5