Massage strange comparison for clang7
kdecore/localization/klocale_kde.cpp:2441:59: error: ordered comparison between pointer and zero ('const void *' and 'int')
    if ((timeFormat().contains(QString::fromLatin1("%I")) > 0) ||
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~

contains() returns bool or QBool, so this was weird to begin with.

PR:		230462
Reported by:	jbeich