multimedia/subtitlecomposer-kde4: unbreak with ICU 63
In file included from src/formats/formatmanager.cpp:54:
In file included from /usr/local/include/unicode/ucsdet.h:28:
/usr/local/include/unicode/localpointer.h:221:34: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    LocalPointer(LocalPointer<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                 ^
/usr/local/include/unicode/localpointer.h:221:40: error: expected ';' at end of declaration list
    LocalPointer(LocalPointer<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                       ^
                                       ;
/usr/local/include/unicode/localpointer.h:366:30: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
    LocalArray(LocalArray<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                             ^
/usr/local/include/unicode/localpointer.h:366:36: error: expected ';' at end of declaration list
    LocalArray(LocalArray<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
                                   ^
                                   ;
In file included from src/formats/formatmanager.cpp:54:
In file included from /usr/local/include/unicode/ucsdet.h:29:
/usr/local/include/unicode/uenum.h:68:1: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration, uenum_close);
^
/usr/local/include/unicode/localpointer.h:493:53: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                    ^
In file included from src/formats/formatmanager.cpp:54:
In file included from /usr/local/include/unicode/ucsdet.h:29:
/usr/local/include/unicode/uenum.h:68:1: error: expected ';' at end of declaration list
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^
In file included from src/formats/formatmanager.cpp:54:
/usr/local/include/unicode/ucsdet.h:106:1: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
U_DEFINE_LOCAL_OPEN_POINTER(LocalUCharsetDetectorPointer, UCharsetDetector, ucsdet_close);
^
/usr/local/include/unicode/localpointer.h:493:53: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                    ^
In file included from src/formats/formatmanager.cpp:54:
/usr/local/include/unicode/ucsdet.h:106:1: error: expected ';' at end of declaration list
/usr/local/include/unicode/localpointer.h:493:60: note: expanded from macro 'U_DEFINE_LOCAL_OPEN_POINTER'
        LocalPointerClassName(LocalPointerClassName &&src) U_NOEXCEPT \
                                                           ^
/usr/local/include/unicode/platform.h:503:23: note: expanded from macro 'U_NOEXCEPT'
 #   define U_NOEXCEPT noexcept
                       ^

Regressed by:	https://github.com/unicode-org/icu/commit/35ce5296c1d3
PR:		232300
Reported by:	antoine (via exp-run)