- Drop run dependency on sysutils/coreutils, checksums are now   calculated by perl functions - Port now compiles fine with warnings switches, don't turn them off - Remove configure PERL_LIBDIR patch, we set PERL_LIBDIR in   CONFIGURE_ENV so perl libdir path is set properly - Remove obsolete REINPLACE_CMD commands, in latest release all that   stuff was fixed and I missed it in last port update - Fix build on current, libdpkg uses md5 checksum functions from libmd   while not listing it as linking dependency, new clang doesn't like it:
  CCLD     dpkg-deb
./lib/dpkg/.libs/libdpkg.a(buffer.o): In function `buffer_digest':
buffer.c:(.text+0x44): undefined reference to `_libmd_MD5Init'
buffer.c:(.text+0x52): undefined reference to `_libmd_MD5Update'
./lib/dpkg/.libs/libdpkg.a(buffer.o): In function `buffer_digest_done':
buffer.c:(.text+0xbf): undefined reference to `_libmd_MD5Final'
./lib/dpkg/.libs/libdpkg.a(buffer.o): In function `buffer_copy':
buffer.c:(.text+0x2fc): undefined reference to `_libmd_MD5Init'
buffer.c:(.text+0x39f): undefined reference to `_libmd_MD5Update'
cc: error: linker command failed with exit code 1 (use -v to see invocation)