audio/icecast-kh: Revert last minute PORTNAME changes and fix build
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: share/icecast/admin/listclients.xsl

- Also install icecast.xml.sample with @sample

PR:		230814
Pointy hat to:	tobik