Fix recursive STAGEDIR referencing.
This was fixed after initial commit in bsd.ocaml.mk r349286.
    ===> Checking for items in STAGEDIR missing from pkg-plist
    Error: Orphaned: @dir /wrkdirs/usr/ports/graphics/ocaml-images/work/stage/usr/local/%%OCAML_SITELIBDIR%%
    Error: Orphaned: @dir /wrkdirs/usr/ports/graphics/ocaml-images/work/stage/usr/local/lib/ocaml
    Error: Orphaned: @dir /wrkdirs/usr/ports/graphics/ocaml-images/work/stage/usr/local/lib
    ...


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@464625 35697150-7ecd-e111-bb59-0022644237b5