security/revelation: Chase dictionary rename from r408137
r408137 of security/cracklib renamed pw_dict to cracklib-words and
revelation now fails to check passwords with 9 characters or more:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/revelation/dialog.py", line 1183, in __cb_changed
    util.check_password(password)
  File "/usr/local/lib/python2.7/site-packages/revelation/util.py", line 97, in check_password
    cracklib.FascistCheck(password, "/usr/local/libdata/cracklib/pw_dict")
OSError: [Errno 2] No such file or directory: '/usr/local/libdata/cracklib/pw_dict.pwd'

PR:		212367
Submitted by:	Tomoaki AOKI <junchoon@dec.sakura.ne.jp>