Fix compilation on GCC-based architectures including and similar to:
  gstgldebug.h:28: error: redefinition of typedef 'GstGLAsyncDebug'

I chose a different approach from the PR.  The trick is that since this
is a slave port, the patchdir by default is from the masterport.  In my
fix, I put the patches back into this port's files/ subdir and do some
Makefile magic to invoke them.

PR:		233788 (based on)
Submitted by:	Piotr Kubaj
Approved by:	portmgr (tier-2 blanket)