misc/nn-insight: fix build with GCC and on head
Add missing includes. This fixes build on stable/12 for powerpc64 (with GCC) and on head with powerpc64. Looking at https://www.freshports.org/misc/nn-insight/, it seems currently doesn't build even on head/amd64, so those includes should fix it.

The original error that made me look into it was:
/wrkdirs/usr/ports/misc/nn-insight/work/nn-insight-1.0.5/tensor.h:18:75: error: 'std::shared_ptr' has not been declared
   18 | bool readTensorDataAsJson(const char *fileName, const TensorShape &shape, std::shared_ptr<const float> &tensorData);
      |                                                                           ^~~

MFH:		2020Q3 (fix build blanket)