devel/babeltrace: fix build on GCC architectures
Requires newer GCC:
integer.c:287: error: #pragma GCC diagnostic not allowed inside functions

Approved by:	mentors (implicit approval)