lang/python32: Fix ABIFLAGS for PYMALLOC option
Investigating the comment regarding a 'configure script bug' lead me
to a bug which manifested itself in 'm' not being added to ABIFLAGS
when PYMALLOC was enabled, not the inability to set
--without-pymalloc using PYMALLOC_CONFIGURE_WITH (options helpers).

The incorrect ABIFLAGS caused packaging failures with default options, so
I'm not sure how this wasn't picked up earlier:

  Error: Orphaned: include/python3.2u/<file>
  <snip>
  Error: Missing: include/python3.2mu/<file>

- Backport an upstream commit [1] to correct the configure bug that never
  made it to the 3.2 branch.
- Use options helpers for PYMALLOC accordingly

While I'm here, clean up after the LIBFFI option addition:

- Sort options variables: OPTIONS_* and *_DESC
- Use OPTIONS helpers

[1] https://hg.python.org/cpython/raw-rev/d158b0a78390

Approved by:	python